version: "3.8"

services:
  frontend-dev-mcp:
    build: .
    container_name: frontend-dev-mcp-server
    restart: unless-stopped

    # Environment variables (override with .env file)
    environment:
      - NODE_ENV=production
      - MCP_SERVER_NAME=frontend-dev-mcp-server
      - LOG_LEVEL=info
      - PLAYWRIGHT_HEADLESS=true
      - PLAYWRIGHT_TIMEOUT=30000
      # Mount your tokens via .env file or secrets
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - FIGMA_ACCESS_TOKEN=${FIGMA_ACCESS_TOKEN}
      - GITHUB_OWNER=${GITHUB_OWNER:-}
      - GITHUB_REPO=${GITHUB_REPO:-}

    # Volumes for persistent data and configuration
    volumes:
      - ./config:/app/config:ro
      - ./output:/app/output
      - ./visual-tests:/app/visual-tests
      - ./logs:/app/logs

    # Network configuration
    networks:
      - mcp-network

    # Resource limits
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: "0.5"
        reservations:
          memory: 512M
          cpus: "0.25"

    # Health check
    healthcheck:
      test: ["CMD", "node", "-e", "console.log('healthy')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Redis for caching (future enhancement)
  redis:
    image: redis:7-alpine
    container_name: mcp-redis
    restart: unless-stopped
    volumes:
      - redis-data:/data
    networks:
      - mcp-network
    profiles:
      - cache

networks:
  mcp-network:
    driver: bridge

volumes:
  redis-data:
# Example .env file contents:
# GITHUB_TOKEN=ghp_your_token_here
# FIGMA_ACCESS_TOKEN=figd_your_token_here
# GITHUB_OWNER=your_username
# GITHUB_REPO=your_repo
