name: Manual Release

on:
  workflow_dispatch:
    inputs:
      version_type:
        description: "Version bump type"
        required: true
        default: "patch"
        type: choice
        options:
          - patch
          - minor
          - major
      release_notes:
        description: "Release notes (optional)"
        required: false
        type: string

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Run linting
        run: npm run lint

      - name: Build project
        run: npm run build

      - name: Configure Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Get current version
        id: current_version
        run: echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

      - name: Bump version
        id: version_bump
        run: |
          NEW_VERSION=$(npm version ${{ github.event.inputs.version_type }} --no-git-tag-version)
          echo "new_version=${NEW_VERSION}" >> $GITHUB_OUTPUT
          echo "version_number=${NEW_VERSION#v}" >> $GITHUB_OUTPUT

      - name: Update CLI version references
        run: |
          sed -i "s/figma-to-react-mcp v[0-9.]*/figma-to-react-mcp v${{ steps.version_bump.outputs.version_number }}/g" src/index.ts

      - name: Commit version bump
        run: |
          git add .
          git commit -m "chore: release ${{ steps.version_bump.outputs.new_version }}"
          git tag ${{ steps.version_bump.outputs.new_version }}

      - name: Publish to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Push changes
        run: |
          git push origin main
          git push origin ${{ steps.version_bump.outputs.new_version }}

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.version_bump.outputs.new_version }}
          release_name: Release ${{ steps.version_bump.outputs.new_version }}
          body: |
            ## 🚀 Release ${{ steps.version_bump.outputs.new_version }}

            **Version Type:** ${{ github.event.inputs.version_type }}
            **Previous Version:** v${{ steps.current_version.outputs.version }}

            ${{ github.event.inputs.release_notes }}

            ### 📦 Installation
            ```bash
            npx figma-to-react-mcp@${{ steps.version_bump.outputs.version_number }} --setup
            ```

            ### 🔄 Upgrade
            ```bash
            npx figma-to-react-mcp@latest --setup
            ```
          draft: false
          prerelease: false
